[tool.poetry]
name = "fastapi101"
version = "0.1.0"
description = ""
authors = ["Dalmo Felipe <dalmo.felipe@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
